global
  daemon

defaults
  mode http
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

frontend https-in
  bind *:443
  default_backend gitlab

backend gitlab
  server debian gitlab.private:80 check