---
- name: Install packages
  apt:
    name: "{{packages}}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - containerd

- name: Copy containerd config
  copy: 
    src: config.toml 
    dest: /etc/containerd/config.toml
  notify: Restart containerd

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/  /
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Change sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    line: 'net.ipv4.ip_forward=1'
    state: present

- name: ip_Forward on
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  
- name: Enable kubelet
  service:
    name: kubelet
    state: started