---
name: Terraform Apply foundation-00
on: workflow_dispatch

env:
  TF_VAR_token: ${{ secrets.TOKEN }}
  TF_VAR_cloud: ${{ secrets.CLOUD }}
  TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
  TF_VAR_domain: ${{ secrets.DOMAIN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        layer: [foundation-00]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        working-directory: ./terraform/${{ github.ref_name }}/${{ matrix.layer }}
        run: |
          terraform init -input=false \
            -backend-config="key=terraform/${{ github.ref_name }}/${{ matrix.layer }}/terraform.tfstate" \
            -backend-config="bucket=${{ secrets.BUCKET }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SECRET_KEY }}"
  
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./terraform/${{ github.ref_name }}/${{ matrix.layer }}
        run: |
          terraform plan -input=false -compact-warnings -out=plan_${{ github.ref_name }}_${{ matrix.layer }}.file
      
      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: plan_${{ github.ref_name }}_${{ matrix.layer }}.file
          path: terraform/${{ github.ref_name }}/${{ matrix.layer }}/plan_${{ github.ref_name }}_${{ matrix.layer }}.file
          retention-days: 7

      - name: Terraform Apply
        working-directory: ./terraform/${{ github.ref_name }}/${{ matrix.layer }}
        run: |
          terraform apply -input=false -compact-warnings plan_${{ github.ref_name }}_${{ matrix.layer }}.file
