name: Terraform init
on: workflow_dispatch

jobs:
  init-:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer: [foundation-00, gitlab-01, platform-02]
    steps:
      - name: Checkout
        uses: actions/checout@4

      - name: init-${matrix.layer}
        uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=./terraform/simple_dev/${matrix.layer} init -backend-config="bucket=${bucket}" \
                                                                          -backend-config="access_key=${access_key}" \
                                                                          -backend-config="secret_key=${secret_key}"