---
name: Terraform init
on: 
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # layer: [foundation-00, gitlab-01, platform-02]
        layer: [foundation-00]
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform -chdir=./terraform/simple_dev/${matrix.layer} init \
              -backend-config="bucket=${{ secrets.BUCKET }}" \
              -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
              -backend-config="secret_key=${{ secrets.SECRET_KEY }}" 