---
name: Terraform Plan
on: workflow_dispatch

env:
  TF_VAR_token: ${{ secrets.TOKEN }}
  TF_VAR_cloud: ${{ secrets.CLOUD }}
  TF_VAR_folder: ${{ secrets.FOLDER }}
  TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer: [foundation-00]
        environment: [simple_dev]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Init
        working-directory: ./terraform/${{ matrix.environment }}/${{ matrix.layer }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.BUCKET }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SECRET_KEY }}"

      - name: Plan
        working-directory: ./terraform/${{ matrix.environment }}/${{ matrix.layer }}
        run: |
          terraform plan -input=false -compact-warnings -out=plan_${{ matrix.environment }}_${{ matrix.layer }}.file
      
      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: plan_${{ matrix.environment }}_${{ matrix.layer }}.file
          path: terraform/${{ matrix.environment }}/${{ matrix.layer }}/plan_${{ matrix.environment }}_${{ matrix.layer }}.file